#ifndef ISD_CONFIG_H
#define ISD_CONFIG_H

#define PARITY (1UL << 31)
#define ISD_EN (1UL << 30)
#define BRAKE_EN (1UL << 29)
#define HIZ_EN (1UL << 28)
#define RVS_DR_EN (1UL << 27)
#define RESYNC_EN (1UL << 26)
#define STAT_BRK_EN (1UL << 25)

#define STAT_DETECT_THR_POS 22
#define STAT_DETECT_THR_5mV (0UL << STAT_DECTECT_THR_POS)
#define STAT_DETECT_THR_10mV (1UL << STAT_DECTECT_THR_POS)
#define STAT_DETECT_THR_15mV (2UL << STAT_DECTECT_THR_POS)
#define STAT_DETECT_THR_20mV (3UL << STAT_DECTECT_THR_POS)
#define STAT_DETECT_THR_25mV (4UL << STAT_DECTECT_THR_POS)
#define STAT_DETECT_THR_30mV (5UL << STAT_DECTECT_THR_POS)
#define STAT_DETECT_THR_50mV (6UL << STAT_DECTECT_THR_POS)
#define STAT_DETECT_THR_100mV (7UL << STAT_DECTECT_THR_POS)

#define BRK_TIME_POS 13
#define BRK_TIME_10ms (0UL << BRK_TIME_POS)
#define BRK_TIME_50ms (1UL << BRK_TIME_POS)
#define BRK_TIME_100ms (2UL << BRK_TIME_POS)
#define BRK_TIME_200ms (3UL << BRK_TIME_POS)
#define BRK_TIME_300ms (4UL << BRK_TIME_POS)
#define BRK_TIME_400ms (5UL << BRK_TIME_POS)
#define BRK_TIME_500ms (6UL << BRK_TIME_POS)
#define BRK_TIME_750ms (7UL << BRK_TIME_POS)
#define BRK_TIME_1s (8UL << BRK_TIME_POS)
#define BRK_TIME_2s (9UL << BRK_TIME_POS)
#define BRK_TIME_3s (aUL << BRK_TIME_POS)
#define BRK_TIME_4s (bUL << BRK_TIME_POS)
#define BRK_TIME_5s (cUL << BRK_TIME_POS)
#define BRK_TIME_7P5s (dUL << BRK_TIME_POS)
#define BRK_TIME_10s (eUL << BRK_TIME_POS)
#define BRK_TIME_15s (fUL << BRK_TIME_POS)


#define HIZ_TIME_POS 9
#define HIZ_TIME_10ms (0UL << HIZ_TIME_POS)
#define HIZ_TIME_50ms (1UL << HIZ_TIME_POS)
#define HIZ_TIME_100ms (2UL << HIZ_TIME_POS)
#define HIZ_TIME_200ms (3UL << HIZ_TIME_POS)
#define HIZ_TIME_300ms (4UL << HIZ_TIME_POS)
#define HIZ_TIME_400ms (5UL << HIZ_TIME_POS)
#define HIZ_TIME_500ms (6UL << HIZ_TIME_POS)
#define HIZ_TIME_750ms (7UL << HIZ_TIME_POS)
#define HIZ_TIME_1s (8UL << HIZ_TIME_POS)
#define HIZ_TIME_2s (9UL << HIZ_TIME_POS)
#define HIZ_TIME_3s (aUL << HIZ_TIME_POS)
#define HIZ_TIME_4s (bUL << HIZ_TIME_POS)
#define HIZ_TIME_5s (cUL << HIZ_TIME_POS)
#define HIZ_TIME_7P5s (dUL << HIZ_TIME_POS)
#define HIZ_TIME_10s (eUL << HIZ_TIME_POS)
#define HIZ_TIME_15s (fUL << HIZ_TIME_POS)

#define STARTUP_BRK_TIME_POS 6
#define STARTUP_BRK_TIME_1ms (0 << STARTUP_BRK_TIME_POS)
#define STARTUP_BRK_TIME_10ms (1 << STARTUP_BRK_TIME_POS)
#define STARTUP_BRK_TIME_25ms (2 << STARTUP_BRK_TIME_POS)
#define STARTUP_BRK_TIME_50ms (3 << STARTUP_BRK_TIME_POS)
#define STARTUP_BRK_TIME_100ms (4 << STARTUP_BRK_TIME_POS)
#define STARTUP_BRK_TIME_250ms (5 << STARTUP_BRK_TIME_POS)
#define STARTUP_BRK_TIME_500ms (6 << STARTUP_BRK_TIME_POS)
#define STARTUP_BRK_TIME_1000ms (7 << STARTUP_BRK_TIME_POS)

#define RESYNC_MIN_THR_POS 3
#define RESYNC_MIN_THR_300mV (1 << RESYNC_MIN_THR_POS)
#define RESYNC_MIN_THR_400mV (2 << RESYNC_MIN_THR_POS)
#define RESYNC_MIN_THR_500mV (3 << RESYNC_MIN_THR_POS)
#define RESYNC_MIN_THR_600mV (4 << RESYNC_MIN_THR_POS)
#define RESYNC_MIN_THR_800mV (5 RESYNC_MIN_THR_POS)
#define RESYNC_MIN_THR_1000mV (6 << RESYNC_MIN_THR_POS)
#define RESYNC_MIN_THR_12500mV (7 << RESYNC_MIN_THR_POS)





#endif
