/*
 * MCT8316_Register.h
 *
 *  Created on: Aug 16, 2023
 *      Author: SpiritBoi
 */

#ifndef INC_MCT8316_DEFINE_H_
#define INC_MCT8316_DEFINE_H_



#define CTRL_WORD_DATA_LENGTH_POS 20
#define DLEN_16BIT 0UL
#define DLEN_32BIT (1UL << CTRL_WORD_DATA_LENGTH_POS)
#define DLEN_64BIT (2UL << CTRL_WORD_DATA_LENGTH_POS)

#define CTRL_WORD_READ_WRITE_POS 23
#define MCT_READ_MODE (1UL << CTRL_WORD_READ_WRITE_POS)
#define MCT_WRITE_MODE (0UL << CTRL_WORD_READ_WRITE_POS)



#define READ_MODE 1
#define WRITE_MODE 0



#endif /* INC_MCT8316_DEFINE_H_ */
